version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: lmq1226lmq
      MYSQL_DATABASE: study
      MYSQL_USER: root
      MYSQL_PASSWORD: lmq1226lmq
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
