version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
        - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/app
      - C:/Application/Programming/Maven/m2:/root/.m2
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: lmq1226lmq  # 设置 root 用户的密码
      MYSQL_DATABASE: kargobang
      # MYSQL_USER 和 MYSQL_PASSWORD 可用于创建一个非 root 用户
      MYSQL_USER: mrowen
      MYSQL_PASSWORD: lmq1226lmq
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
