server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lmq1226lmq
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  # 修复swagger版本不匹配bug
  mail:
    host: smtp.qq.com
    username: lmq122677@qq.com
    password: rgpyxammhfsfjfgc